name: Build wxPython
on:
  push:
    paths-ignore:
      - 'docs/**'
  workflow_dispatch:
  release:
    types: [published]
jobs:
    build:
        name: Build wxPython
        runs-on: macos-15
        if: github.repository_owner == 'pyquick'
        permissions:
            contents: write
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python 3.13
              uses: actions/setup-python@v5
              with:
                python-version: '3.13'
            - name: Install Dependencies
              run: |
                /Library/Frameworks/Python.framework/Versions/3.13/bin/python3 -m pip install -r requirements.txt
            - name: Build Apps
              run: |
                /Library/Frameworks/Python.framework/Versions/3.13/bin/python3 build_project.py
            - name: Delete previous pre-release
              uses: dev-drprasad/delete-older-releases@v0.3.4
              with:
                keep_latest: 0
                delete_prerelease_only: true
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: Create (Pre-)Release on Push
              if: github.event_name == 'push'
              uses: softprops/action-gh-release@v2
              with:
                tag_name: 2.0.0B1
                name: 2.0.0 Beta 1
                body: ${{ github.event.head_commit.message }}
                prerelease: true
                files: |
                    ./dist/Converter.zip
                    ./dist/convert.bin
                    ./dist/convertzip.bin
                    


