name: Build wxPython
on:
  push:
    paths-ignore:
      - 'docs/**'
  workflow_dispatch:
  release:
    types: [published]
jobs:
    build:
        name: Build wxPython
        runs-on: macos-15
        if: github.repository_owner == 'pyquick'
        permissions:
            contents: write
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python 3.13
              uses: actions/setup-python@v5
              with:
                python-version: '3.13'
            - name: Install Dependencies
              run: |
                chmod +x build_nk.command
                /Library/Frameworks/Python.framework/Versions/3.13/bin/python3 -m pip install -r requirements.txt
                
            - name: Build Apps
              run: |
                ./build_nk.command
                /Library/Frameworks/Python.framework/Versions/3.13/bin/python3 patch.py
            - name: Create (Pre-)Release on Push
              if: github.event_name == 'push'
              uses: softprops/action-gh-release@v2
              with:
                tag_name: 0.91
                name: 1.0Pre2
                body: ${{ github.event.head_commit.message }}
                prerelease: true
                files: |
                    ./dist/gui_converter.app
                    


